### ISSUE TITLE
pnpm complains about peer dependency issues

### ISSUE THREAD

**Issue by lirantal** [surjithctly/astroship#14]
```
 WARN  Issues with peer dependencies found
.
├─┬ @astrojs/mdx 0.16.0
│ └─┬ @mdx-js/rollup 2.2.1
│   ├── ✕ missing peer rollup@>=2
│   └─┬ @rollup/pluginutils 5.0.2
│     └── ✕ missing peer rollup@^1.20.0||^2.0.0||^3.0.0
└─┬ @astrojs/vercel 3.1.2
  └─┬ @vercel/analytics 0.1.9
    └── ✕ missing peer react@^16.8||^17||^18
Peer dependencies that should be installed:
  react@^16.8||^17||^18                      rollup@">=2.0.0 <3.0.0 || >=3.0.0 <4.0.0"  

Done in 2.1s
```

The last one about `react` missing is because I added the `vercel` SSR integration, though I did that through `pnpm astro add vercel` and would think it would have worked that out.

**Comment by surjithctly** [comment]
Few packages has been updated recently. are you using the latest one? if not try again with that?

**Comment by lirantal** [comment]
I'm using the latest repo clone, yes. Not entirely sure there about the action item so will close and update if there's anything else.
