### ISSUE TITLE
Problems with blog title alignment with custom font size

### ISSUE THREAD

**Issue by zk-g** [surjithctly/astroship#15]
browser: chrome / latest (font size: 18)

![image](https://user-images.githubusercontent.com/17980844/221377946-6faae7fa-9717-41bb-9b52-842b6af8df72.png)

I don't know if it's the desired.

If it's not I think it could be changend by using same classes as the box below, it doesn't seem to casuse any trouble with responisvness 

![image](https://user-images.githubusercontent.com/17980844/221377997-7ce50d2f-fd89-4436-b17c-7d4418a60e5c.png)

**Comment by surjithctly** [comment]
Seems i cannot replicate it here. Actually the left alignment was correct. Can you share a URL where I can see the issue?

**Comment by zk-g** [comment]
To replicate you have to increase the browser font size

**Comment by surjithctly** [comment]
Thank you. It's fixed.
