### ISSUE TITLE
Suggestion: Add a custom 404 page

### ISSUE THREAD

**Issue by alexpyzhianov** [surjithctly/astroship#19]
Not sure if it's a good idea or not, but Astro gives you the option to create your own custom 404 page. The docs:
https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page

How about we add a simple `404.astro` to this template? Some of the reasons for this IMO are:
1. A custom 404 page makes any site feel a little more user-friendly
2. It's a great way to show someone new to Astro that such option (having a custom 404 page) even exists
3. It's easy to delete in case you don't want to have one

Anyway, what are your thoughts on this? I'm building one right now for my personal portfolio (based on Astroship), so I can probably submit a PR pretty easily

**Comment by surjithctly** [comment]
Agreed, If you can submit a PR that would be great.
