### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by SahilFruitwala** [surjithctly/astroship#22]
Can you suggest and guide me on how to add a newsletter? I saw the contact form but didn't understand how would I make API calls on that. I am still learning Astro.

**Comment by SahilFruitwala** [comment]
NM did it. Thanks for the theme 🙌🏼

**Comment by Vii-Hunnid** [comment]
Hey Surjith S M and SahilFruitwala, my apologies if I pronounce your names wrong.
My real name is Isaac and I am from South Africa, I need help if possible.

I am following your Astro project here trying to build my own api that can help me send emails.
But I am stuck here "    fetch("https://api.web3forms.com/submit", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: json,
    })"
    
    This is how mine looks currently "        const response = await fetch("https://api.staquitize.io/send-email", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(email.value),
        });"
        But I cannot get it to work or know how to connect it well.
    
    How do I build one that I can use to send emails Just like yours?
    If possible guys can you please help.
    
    Thank you,
    Kind regards,
