### ISSUE TITLE
What is the proper way to attribute template creators?

### ISSUE THREAD

**Issue by marekbrze** [surjithctly/astroship#24]
Hi,

I am a little bit lost in terms of proper attribution for usage of the template.

Is `Website was created using Astroship template` info in the footer with a link to Github repo enough?

Or should I add additional info? 🤔

**Comment by surjithctly** [comment]
That is perfectly fine. or just a link in the footer to [Web3Templates](https://web3templates.com/templates/astroship-starter-website-template-for-astro) is also fine. (links to astroship page)

**Comment by marekbrze** [comment]
Thank you for the quick reply!

Btw the template is awesome ❤️
