### ISSUE TITLE
Interactive drop down elements in nav bar not working.

### ISSUE THREAD

**Issue by chartley1988** [surjithctly/astroship#37]
Seems like something broke with commit `5f36154`, the introduction of Astro 2.9.7. From then on, I can't get drop downs to work in nav bars.

**Comment by surjithctly** [comment]
hey, can you tell me if its working with latest Astroship + Astro Navbar?

**Comment by chartley1988** [comment]
It's working well! Thanks for the update :)

**Comment by chartley1988** [comment]
Fixed!
