### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by lanbau** [surjithctly/astroship#4]
Hi nice theme. Is pagination out of the box for the blog page?

**Comment by surjithctly** [comment]
Not yet

**Comment by saif71** [comment]
@surjithctly I know it is too much to ask but do you have any plan to implement paginations?

**Comment by surjithctly** [comment]
@saif71 yes, I think I can do it. but can't confirm yet.

**Comment by surjithctly** [comment]
This is implemented in the Blog Page of the Pro version. 

https://astroship-pro.web3templates.com/
