### ISSUE TITLE
Pro version too slow

### ISSUE THREAD

**Issue by ishandutta2007** [surjithctly/astroship#42]
Free version scores 100 but pro version scores in 80s, such a huge speed difference.
https://pagespeed.web.dev/analysis/https-astroship-pro-web3templates-com/5f4balshzj?form_factor=mobile

It beats the purpose of migrating from react/nextjs to a modern high performance claiming framework like Astro.
I am sure we are missing something fundamental in here.
Look at https://github.com/onwidget/astrowind  it scores 100

**Comment by surjithctly** [comment]
Thanks for flagging. Performance upgrade is on the way 👍

**Comment by surjithctly** [comment]
It has been updated and it got **99** on mobile and **100** on desktop 🥳

**Comment by ishandutta2007** [comment]
I can't find 99 on mobile. tested multiple times. Have you not deployed it on web3templates domain ?
![Screenshot 2023-10-20 at 10 58 58 PM](https://github.com/surjithctly/astroship/assets/2527354/14673f63-6ea3-403f-ae87-882d0467effb)

**Comment by surjithctly** [comment]
That’s strange. Here’s my test results 

https://pagespeed.web.dev/analysis/https-astroship-pro-web3templates-com/qa606ptzlp?form_factor=mobile

Can you share yours?

**Comment by ishandutta2007** [comment]
I shared above. Yes really strange
