### ISSUE TITLE
Pricing: Up to 20 users what does it mean  ?

### ISSUE THREAD

**Issue by danaoairuike** [surjithctly/astroship#49]
Hi, what do you mean by "Up to 20 users" ? 20 engineers ? 20 projects? 20 team members? 20 customers ?Thanks

**Comment by surjithctly** [comment]
It's just a dummy text for this template. you are free to change it.

**Comment by guiyumin** [comment]
> It's just a dummy text for this template. you are free to change it.

so, it's free to use your template? including the pro version, https://astroship-pro.web3templates.com/  ?

**Comment by surjithctly** [comment]
Yeah, The Pro version is a one-time purchase. [Purchase Link](https://web3templates.com/templates/astroship-pro-astro-saas-website-template)
