### ISSUE TITLE
Hero Image not rendered on Microsoft Edge browser

### ISSUE THREAD

**Issue by rnwolf** [surjithctly/astroship#5]
Great Astro Theme.  
Noticed that the spaceship hero image does not render on Microsoft Edge browser on Win 11.  
Works fine in Firefox, but as Edge has about 10% market share it might worth providing alternate format.

![image](https://user-images.githubusercontent.com/117415/210277608-e0eb196b-9129-4291-b2eb-c504f8708065.png)

**Comment by rnwolf** [comment]
Interesting, I see that Edge does not support avif images.
I usually use Chrome (Reinstalled Windows 11 and just stayed with Edge last week. ), and assumed that Edge would as also support avif. :(

https://www.reddit.com/r/webdev/comments/wprmzg/how_can_avif_images_be_supported_in_chrome_and/

**Comment by surjithctly** [comment]
Thanks for noticing. Let me swap it with `picture` element so it fallbacks on un supported browsers.
