### ISSUE TITLE
What does GPL license mean for a Astro template? 

### ISSUE THREAD

**Issue by aminya** [surjithctly/astroship#50]
Hi, I wanted to use the [free version](https://astroship.web3templates.com/) of this template to build a website. However, I am confused as to what GPL means in this case. The HTML code is technically accessible through the browser, so does that mean I can create websites using this template without paying for the Pro version?

**Comment by surjithctly** [comment]
Hi,

Yes, you are free to use the Free version. You have to keep the license and copyright back to this original template.
